CreateObject("SAPI.SpVoice").Speak"过年好啊,我要用13种语言给您拜年啦"
Dim AutoTime
AutoTime = 50
Set WS=WScript.CreateObject("WScript.Shell")
WS.run("notepad"),3
WScript.Sleep 500
WS.AppActivate("notepad")
WS.SendKeys "+"
WScript.Sleep AutoTime
WS.SendKeys "p"
WScript.Sleep AutoTime
WS.SendKeys "r"
WScript.Sleep AutoTime
WS.SendKeys "i"
WScript.Sleep AutoTime
WS.SendKeys "n"
WScript.Sleep AutoTime
WS.SendKeys "t"
WScript.Sleep AutoTime
WS.SendKeys "_"
WScript.Sleep AutoTime
WS.SendKeys "r"
WScript.Sleep AutoTime
WS.SendKeys "{(}"
WScript.Sleep AutoTime
WS.SendKeys "'"
WScript.Sleep AutoTime
WS.SendKeys "+"
WScript.Sleep AutoTime
WS.SendKeys "x"
WScript.Sleep AutoTime
WS.SendKeys "i"
WScript.Sleep AutoTime
WS.SendKeys "n"
WScript.Sleep AutoTime
WS.SendKeys "n"
WScript.Sleep AutoTime
WS.SendKeys "i"
WScript.Sleep AutoTime
WS.SendKeys "a"
WScript.Sleep AutoTime
WS.SendKeys "n"
WScript.Sleep AutoTime
WS.SendKeys "k"
WScript.Sleep AutoTime
WS.SendKeys "u"
WScript.Sleep AutoTime
WS.SendKeys "a"
WScript.Sleep AutoTime
WS.SendKeys "i"
WScript.Sleep AutoTime
WS.SendKeys "l"
WScript.Sleep AutoTime
WS.SendKeys "e"
WScript.Sleep AutoTime
WS.SendKeys "1"
WScript.Sleep AutoTime
WS.SendKeys "+"
WScript.Sleep AutoTime
WS.SendKeys "'"
WScript.Sleep AutoTime
WS.SendKeys "{)}"
WScript.Sleep AutoTime
WS.SendKeys ";"
WScript.Sleep 1000
WS.SendKeys "{ENTER}"


WScript.Sleep AutoTime
WS.SendKeys "v"
WScript.Sleep AutoTime
WS.SendKeys "a"
WScript.Sleep AutoTime
WS.SendKeys "r"
WScript.Sleep AutoTime
WS.SendKeys "_"
WScript.Sleep AutoTime
WS.SendKeys "d"
WScript.Sleep AutoTime
WS.SendKeys "u"
WScript.Sleep AutoTime
WS.SendKeys "m"
WScript.Sleep AutoTime
WS.SendKeys "p"
WScript.Sleep AutoTime
WS.SendKeys "{(}"
WScript.Sleep AutoTime
WS.SendKeys "'"
WScript.Sleep AutoTime
WS.SendKeys "+"
WScript.Sleep AutoTime
WS.SendKeys "x"
WScript.Sleep AutoTime
WS.SendKeys "i"
WScript.Sleep AutoTime
WS.SendKeys "n"
WScript.Sleep AutoTime
WS.SendKeys "n"
WScript.Sleep AutoTime
WS.SendKeys "i"
WScript.Sleep AutoTime
WS.SendKeys "a"
WScript.Sleep AutoTime
WS.SendKeys "n"
WScript.Sleep AutoTime
WS.SendKeys "k"
WScript.Sleep AutoTime
WS.SendKeys "u"
WScript.Sleep AutoTime
WS.SendKeys "a"
WScript.Sleep AutoTime
WS.SendKeys "i"
WScript.Sleep AutoTime
WS.SendKeys "l"
WScript.Sleep AutoTime
WS.SendKeys "e"
WScript.Sleep AutoTime
WS.SendKeys "1"
WScript.Sleep AutoTime
WS.SendKeys "+"
WScript.Sleep AutoTime
WS.SendKeys "'"
WScript.Sleep AutoTime
WS.SendKeys "{)}"
WScript.Sleep AutoTime
WS.SendKeys ";"
WScript.Sleep 1000
WS.SendKeys "{ENTER}"


WScript.Sleep AutoTime
WS.SendKeys "N"
WScript.Sleep AutoTime
WS.SendKeys "S"
WScript.Sleep AutoTime
WS.SendKeys "L"
WScript.Sleep AutoTime
WS.SendKeys "o"
WScript.Sleep AutoTime
WS.SendKeys "g"
WScript.Sleep AutoTime
WS.SendKeys "{(}"
WScript.Sleep AutoTime
WS.SendKeys "@"
WScript.Sleep AutoTime
WS.SendKeys """"
WScript.Sleep AutoTime
WS.SendKeys "+"
WScript.Sleep AutoTime
WS.SendKeys "x"
WScript.Sleep AutoTime
WS.SendKeys "i"
WScript.Sleep AutoTime
WS.SendKeys "n"
WScript.Sleep AutoTime
WS.SendKeys "n"
WScript.Sleep AutoTime
WS.SendKeys "i"
WScript.Sleep AutoTime
WS.SendKeys "a"
WScript.Sleep AutoTime
WS.SendKeys "n"
WScript.Sleep AutoTime
WS.SendKeys "k"
WScript.Sleep AutoTime
WS.SendKeys "u"
WScript.Sleep AutoTime
WS.SendKeys "a"
WScript.Sleep AutoTime
WS.SendKeys "i"
WScript.Sleep AutoTime
WS.SendKeys "l"
WScript.Sleep AutoTime
WS.SendKeys "e"
WScript.Sleep AutoTime
WS.SendKeys "1"
WScript.Sleep AutoTime
WS.SendKeys "+"
WScript.Sleep AutoTime
WS.SendKeys """"
WScript.Sleep AutoTime
WS.SendKeys "{)}"
WScript.Sleep AutoTime
WS.SendKeys ";"
WScript.Sleep 1000
WS.SendKeys "{ENTER}"


WScript.Sleep AutoTime
WS.SendKeys "S"
WScript.Sleep AutoTime
WS.SendKeys "y"
WScript.Sleep AutoTime
WS.SendKeys "s"
WScript.Sleep AutoTime
WS.SendKeys "t"
WScript.Sleep AutoTime
WS.SendKeys "e"
WScript.Sleep AutoTime
WS.SendKeys "m"
WScript.Sleep AutoTime
WS.SendKeys "."
WScript.Sleep AutoTime
WS.SendKeys "o"
WScript.Sleep AutoTime
WS.SendKeys "u"
WScript.Sleep AutoTime
WS.SendKeys "t"
WScript.Sleep AutoTime
WS.SendKeys "."
WScript.Sleep AutoTime
WS.SendKeys "p"
WScript.Sleep AutoTime
WS.SendKeys "r"
WScript.Sleep AutoTime
WS.SendKeys "i"
WScript.Sleep AutoTime
WS.SendKeys "n"
WScript.Sleep AutoTime
WS.SendKeys "t"
WScript.Sleep AutoTime
WS.SendKeys "l"
WScript.Sleep AutoTime
WS.SendKeys "n"
WScript.Sleep AutoTime
WS.SendKeys "{(}"
WScript.Sleep AutoTime
WS.SendKeys """"
WScript.Sleep AutoTime
WS.SendKeys "+"
WScript.Sleep AutoTime
WS.SendKeys "x"
WScript.Sleep AutoTime
WS.SendKeys "i"
WScript.Sleep AutoTime
WS.SendKeys "n"
WScript.Sleep AutoTime
WS.SendKeys "n"
WScript.Sleep AutoTime
WS.SendKeys "i"
WScript.Sleep AutoTime
WS.SendKeys "a"
WScript.Sleep AutoTime
WS.SendKeys "n"
WScript.Sleep AutoTime
WS.SendKeys "k"
WScript.Sleep AutoTime
WS.SendKeys "u"
WScript.Sleep AutoTime
WS.SendKeys "a"
WScript.Sleep AutoTime
WS.SendKeys "i"
WScript.Sleep AutoTime
WS.SendKeys "l"
WScript.Sleep AutoTime
WS.SendKeys "e"
WScript.Sleep AutoTime
WS.SendKeys "1"
WScript.Sleep AutoTime
WS.SendKeys "+"
WScript.Sleep AutoTime
WS.SendKeys """"
WScript.Sleep AutoTime
WS.SendKeys "{)}"
WScript.Sleep AutoTime
WS.SendKeys ";"
WScript.Sleep 1000
WS.SendKeys "{ENTER}"


WScript.Sleep AutoTime
WS.SendKeys "c"
WScript.Sleep AutoTime
WS.SendKeys "o"
WScript.Sleep AutoTime
WS.SendKeys "n"
WScript.Sleep AutoTime
WS.SendKeys "s"
WScript.Sleep AutoTime
WS.SendKeys "o"
WScript.Sleep AutoTime
WS.SendKeys "l"
WScript.Sleep AutoTime
WS.SendKeys "e"
WScript.Sleep AutoTime
WS.SendKeys "."
WScript.Sleep AutoTime
WS.SendKeys "l"
WScript.Sleep AutoTime
WS.SendKeys "o"
WScript.Sleep AutoTime
WS.SendKeys "g"
WScript.Sleep AutoTime
WS.SendKeys "{(}"
WScript.Sleep AutoTime
WS.SendKeys """"
WScript.Sleep AutoTime
WS.SendKeys "+"
WScript.Sleep AutoTime
WS.SendKeys "x"
WScript.Sleep AutoTime
WS.SendKeys "i"
WScript.Sleep AutoTime
WS.SendKeys "n"
WScript.Sleep AutoTime
WS.SendKeys "n"
WScript.Sleep AutoTime
WS.SendKeys "i"
WScript.Sleep AutoTime
WS.SendKeys "a"
WScript.Sleep AutoTime
WS.SendKeys "n"
WScript.Sleep AutoTime
WS.SendKeys "k"
WScript.Sleep AutoTime
WS.SendKeys "u"
WScript.Sleep AutoTime
WS.SendKeys "a"
WScript.Sleep AutoTime
WS.SendKeys "i"
WScript.Sleep AutoTime
WS.SendKeys "l"
WScript.Sleep AutoTime
WS.SendKeys "e"
WScript.Sleep AutoTime
WS.SendKeys "1"
WScript.Sleep AutoTime
WS.SendKeys "+"
WScript.Sleep AutoTime
WS.SendKeys """"
WScript.Sleep AutoTime
WS.SendKeys "{)}"
WScript.Sleep AutoTime
WS.SendKeys ";"
WScript.Sleep 1000
WS.SendKeys "{ENTER}"


WScript.Sleep AutoTime
WS.SendKeys "p"
WScript.Sleep AutoTime
WS.SendKeys "r"
WScript.Sleep AutoTime
WS.SendKeys "i"
WScript.Sleep AutoTime
WS.SendKeys "n"
WScript.Sleep AutoTime
WS.SendKeys "t"
WScript.Sleep AutoTime
WS.SendKeys "{(}"
WScript.Sleep AutoTime
WS.SendKeys """"
WScript.Sleep AutoTime
WS.SendKeys "+"
WScript.Sleep AutoTime
WS.SendKeys "x"
WScript.Sleep AutoTime
WS.SendKeys "i"
WScript.Sleep AutoTime
WS.SendKeys "n"
WScript.Sleep AutoTime
WS.SendKeys "n"
WScript.Sleep AutoTime
WS.SendKeys "i"
WScript.Sleep AutoTime
WS.SendKeys "a"
WScript.Sleep AutoTime
WS.SendKeys "n"
WScript.Sleep AutoTime
WS.SendKeys "k"
WScript.Sleep AutoTime
WS.SendKeys "u"
WScript.Sleep AutoTime
WS.SendKeys "a"
WScript.Sleep AutoTime
WS.SendKeys "i"
WScript.Sleep AutoTime
WS.SendKeys "l"
WScript.Sleep AutoTime
WS.SendKeys "e"
WScript.Sleep AutoTime
WS.SendKeys "1"
WScript.Sleep AutoTime
WS.SendKeys "+"
WScript.Sleep AutoTime
WS.SendKeys """"
WScript.Sleep AutoTime
WS.SendKeys "{)}"
WScript.Sleep AutoTime
WS.SendKeys ";"
WScript.Sleep 1000
WS.SendKeys "{ENTER}"


WScript.Sleep AutoTime
WS.SendKeys "p"
WScript.Sleep AutoTime
WS.SendKeys "r"
WScript.Sleep AutoTime
WS.SendKeys "i"
WScript.Sleep AutoTime
WS.SendKeys "n"
WScript.Sleep AutoTime
WS.SendKeys "t"
WScript.Sleep AutoTime
WS.SendKeys "f"
WScript.Sleep AutoTime
WS.SendKeys "{(}"
WScript.Sleep AutoTime
WS.SendKeys """"
WScript.Sleep AutoTime
WS.SendKeys "+"
WScript.Sleep AutoTime
WS.SendKeys "x"
WScript.Sleep AutoTime
WS.SendKeys "i"
WScript.Sleep AutoTime
WS.SendKeys "n"
WScript.Sleep AutoTime
WS.SendKeys "n"
WScript.Sleep AutoTime
WS.SendKeys "i"
WScript.Sleep AutoTime
WS.SendKeys "a"
WScript.Sleep AutoTime
WS.SendKeys "n"
WScript.Sleep AutoTime
WS.SendKeys "k"
WScript.Sleep AutoTime
WS.SendKeys "u"
WScript.Sleep AutoTime
WS.SendKeys "a"
WScript.Sleep AutoTime
WS.SendKeys "i"
WScript.Sleep AutoTime
WS.SendKeys "l"
WScript.Sleep AutoTime
WS.SendKeys "e"
WScript.Sleep AutoTime
WS.SendKeys "1"
WScript.Sleep AutoTime
WS.SendKeys "+"
WScript.Sleep AutoTime
WS.SendKeys """"
WScript.Sleep AutoTime
WS.SendKeys "{)}"
WScript.Sleep AutoTime
WS.SendKeys ";"
WScript.Sleep 1000
WS.SendKeys "{ENTER}"


WScript.Sleep AutoTime
WS.SendKeys "c"
WScript.Sleep AutoTime
WS.SendKeys "o"
WScript.Sleep AutoTime
WS.SendKeys "u"
WScript.Sleep AutoTime
WS.SendKeys "t"
WScript.Sleep AutoTime
WS.SendKeys "<"
WScript.Sleep AutoTime
WS.SendKeys "<"
WScript.Sleep AutoTime
WS.SendKeys """"
WScript.Sleep AutoTime
WS.SendKeys "+"
WScript.Sleep AutoTime
WS.SendKeys "x"
WScript.Sleep AutoTime
WS.SendKeys "i"
WScript.Sleep AutoTime
WS.SendKeys "n"
WScript.Sleep AutoTime
WS.SendKeys "n"
WScript.Sleep AutoTime
WS.SendKeys "i"
WScript.Sleep AutoTime
WS.SendKeys "a"
WScript.Sleep AutoTime
WS.SendKeys "n"
WScript.Sleep AutoTime
WS.SendKeys "k"
WScript.Sleep AutoTime
WS.SendKeys "u"
WScript.Sleep AutoTime
WS.SendKeys "a"
WScript.Sleep AutoTime
WS.SendKeys "i"
WScript.Sleep AutoTime
WS.SendKeys "l"
WScript.Sleep AutoTime
WS.SendKeys "e"
WScript.Sleep AutoTime
WS.SendKeys "1"
WScript.Sleep AutoTime
WS.SendKeys "+"
WScript.Sleep AutoTime
WS.SendKeys """"
WScript.Sleep AutoTime
WS.SendKeys "<"
WScript.Sleep AutoTime
WS.SendKeys "<"
WScript.Sleep AutoTime
WS.SendKeys " "
WScript.Sleep AutoTime
WS.SendKeys "e"
WScript.Sleep AutoTime
WS.SendKeys "n"
WScript.Sleep AutoTime
WS.SendKeys "d"
WScript.Sleep AutoTime
WS.SendKeys "l"
WScript.Sleep AutoTime
WS.SendKeys ";"
WScript.Sleep 1000
WS.SendKeys "{ENTER}"


WScript.Sleep AutoTime
WS.SendKeys "C"
WScript.Sleep AutoTime
WS.SendKeys "o"
WScript.Sleep AutoTime
WS.SendKeys "n"
WScript.Sleep AutoTime
WS.SendKeys "s"
WScript.Sleep AutoTime
WS.SendKeys "o"
WScript.Sleep AutoTime
WS.SendKeys "l"
WScript.Sleep AutoTime
WS.SendKeys "e"
WScript.Sleep AutoTime
WS.SendKeys "."
WScript.Sleep AutoTime
WS.SendKeys "W"
WScript.Sleep AutoTime
WS.SendKeys "r"
WScript.Sleep AutoTime
WS.SendKeys "i"
WScript.Sleep AutoTime
WS.SendKeys "t"
WScript.Sleep AutoTime
WS.SendKeys "e"
WScript.Sleep AutoTime
WS.SendKeys "L"
WScript.Sleep AutoTime
WS.SendKeys "i"
WScript.Sleep AutoTime
WS.SendKeys "n"
WScript.Sleep AutoTime
WS.SendKeys "e"
WScript.Sleep AutoTime
WS.SendKeys "{(}"
WScript.Sleep AutoTime
WS.SendKeys """"
WScript.Sleep AutoTime
WS.SendKeys "+"
WScript.Sleep AutoTime
WS.SendKeys "x"
WScript.Sleep AutoTime
WS.SendKeys "i"
WScript.Sleep AutoTime
WS.SendKeys "n"
WScript.Sleep AutoTime
WS.SendKeys "n"
WScript.Sleep AutoTime
WS.SendKeys "i"
WScript.Sleep AutoTime
WS.SendKeys "a"
WScript.Sleep AutoTime
WS.SendKeys "n"
WScript.Sleep AutoTime
WS.SendKeys "k"
WScript.Sleep AutoTime
WS.SendKeys "u"
WScript.Sleep AutoTime
WS.SendKeys "a"
WScript.Sleep AutoTime
WS.SendKeys "i"
WScript.Sleep AutoTime
WS.SendKeys "l"
WScript.Sleep AutoTime
WS.SendKeys "e"
WScript.Sleep AutoTime
WS.SendKeys "1"
WScript.Sleep AutoTime
WS.SendKeys "+"
WScript.Sleep AutoTime
WS.SendKeys """"
WScript.Sleep AutoTime
WS.SendKeys "{)}"
WScript.Sleep AutoTime
WS.SendKeys ";"
WScript.Sleep AutoTime
WS.SendKeys " "
WScript.Sleep 1000
WS.SendKeys "{ENTER}"


WScript.Sleep AutoTime
WS.SendKeys "f"
WScript.Sleep AutoTime
WS.SendKeys "m"
WScript.Sleep AutoTime
WS.SendKeys "t"
WScript.Sleep AutoTime
WS.SendKeys "."
WScript.Sleep AutoTime
WS.SendKeys "P"
WScript.Sleep AutoTime
WS.SendKeys "r"
WScript.Sleep AutoTime
WS.SendKeys "i"
WScript.Sleep AutoTime
WS.SendKeys "n"
WScript.Sleep AutoTime
WS.SendKeys "t"
WScript.Sleep AutoTime
WS.SendKeys "l"
WScript.Sleep AutoTime
WS.SendKeys "n"
WScript.Sleep AutoTime
WS.SendKeys "{(}"
WScript.Sleep AutoTime
WS.SendKeys """"
WScript.Sleep AutoTime
WS.SendKeys "+"
WScript.Sleep AutoTime
WS.SendKeys "x"
WScript.Sleep AutoTime
WS.SendKeys "i"
WScript.Sleep AutoTime
WS.SendKeys "n"
WScript.Sleep AutoTime
WS.SendKeys "n"
WScript.Sleep AutoTime
WS.SendKeys "i"
WScript.Sleep AutoTime
WS.SendKeys "a"
WScript.Sleep AutoTime
WS.SendKeys "n"
WScript.Sleep AutoTime
WS.SendKeys "k"
WScript.Sleep AutoTime
WS.SendKeys "u"
WScript.Sleep AutoTime
WS.SendKeys "a"
WScript.Sleep AutoTime
WS.SendKeys "i"
WScript.Sleep AutoTime
WS.SendKeys "l"
WScript.Sleep AutoTime
WS.SendKeys "e"
WScript.Sleep AutoTime
WS.SendKeys "1"
WScript.Sleep AutoTime
WS.SendKeys "+"
WScript.Sleep AutoTime
WS.SendKeys """"
WScript.Sleep AutoTime
WS.SendKeys "{)}"
WScript.Sleep AutoTime
WS.SendKeys ";"
WScript.Sleep 1000
WS.SendKeys "{ENTER}"


WScript.Sleep AutoTime
WS.SendKeys "R"
WScript.Sleep AutoTime
WS.SendKeys "e"
WScript.Sleep AutoTime
WS.SendKeys "s"
WScript.Sleep AutoTime
WS.SendKeys "p"
WScript.Sleep AutoTime
WS.SendKeys "o"
WScript.Sleep AutoTime
WS.SendKeys "n"
WScript.Sleep AutoTime
WS.SendKeys "s"
WScript.Sleep AutoTime
WS.SendKeys "e"
WScript.Sleep AutoTime
WS.SendKeys "."
WScript.Sleep AutoTime
WS.SendKeys "W"
WScript.Sleep AutoTime
WS.SendKeys "r"
WScript.Sleep AutoTime
WS.SendKeys "i"
WScript.Sleep AutoTime
WS.SendKeys "t"
WScript.Sleep AutoTime
WS.SendKeys "e"
WScript.Sleep AutoTime
WS.SendKeys "{(}"
WScript.Sleep AutoTime
WS.SendKeys """"
WScript.Sleep AutoTime
WS.SendKeys "+"
WScript.Sleep AutoTime
WS.SendKeys "x"
WScript.Sleep AutoTime
WS.SendKeys "i"
WScript.Sleep AutoTime
WS.SendKeys "n"
WScript.Sleep AutoTime
WS.SendKeys "n"
WScript.Sleep AutoTime
WS.SendKeys "i"
WScript.Sleep AutoTime
WS.SendKeys "a"
WScript.Sleep AutoTime
WS.SendKeys "n"
WScript.Sleep AutoTime
WS.SendKeys "k"
WScript.Sleep AutoTime
WS.SendKeys "u"
WScript.Sleep AutoTime
WS.SendKeys "a"
WScript.Sleep AutoTime
WS.SendKeys "i"
WScript.Sleep AutoTime
WS.SendKeys "l"
WScript.Sleep AutoTime
WS.SendKeys "e"
WScript.Sleep AutoTime
WS.SendKeys "1"
WScript.Sleep AutoTime
WS.SendKeys "+"
WScript.Sleep AutoTime
WS.SendKeys """"
WScript.Sleep AutoTime
WS.SendKeys "{)}"
WScript.Sleep AutoTime
WS.SendKeys ";"
WScript.Sleep 1000
WS.SendKeys "{ENTER}"


WScript.Sleep AutoTime
WS.SendKeys "a"
WScript.Sleep AutoTime
WS.SendKeys "l"
WScript.Sleep AutoTime
WS.SendKeys "e"
WScript.Sleep AutoTime
WS.SendKeys "r"
WScript.Sleep AutoTime
WS.SendKeys "t"
WScript.Sleep AutoTime
WS.SendKeys "{(}"
WScript.Sleep AutoTime
WS.SendKeys """"
WScript.Sleep AutoTime
WS.SendKeys "+"
WScript.Sleep AutoTime
WS.SendKeys "x"
WScript.Sleep AutoTime
WS.SendKeys "i"
WScript.Sleep AutoTime
WS.SendKeys "n"
WScript.Sleep AutoTime
WS.SendKeys "n"
WScript.Sleep AutoTime
WS.SendKeys "i"
WScript.Sleep AutoTime
WS.SendKeys "a"
WScript.Sleep AutoTime
WS.SendKeys "n"
WScript.Sleep AutoTime
WS.SendKeys "k"
WScript.Sleep AutoTime
WS.SendKeys "u"
WScript.Sleep AutoTime
WS.SendKeys "a"
WScript.Sleep AutoTime
WS.SendKeys "i"
WScript.Sleep AutoTime
WS.SendKeys "l"
WScript.Sleep AutoTime
WS.SendKeys "e"
WScript.Sleep AutoTime
WS.SendKeys "1"
WScript.Sleep AutoTime
WS.SendKeys "+"
WScript.Sleep AutoTime
WS.SendKeys """"
WScript.Sleep AutoTime
WS.SendKeys "{)}"
WScript.Sleep 1000
WS.SendKeys "{ENTER}"


WScript.Sleep AutoTime
WS.SendKeys "e"
WScript.Sleep AutoTime
WS.SendKeys "c"
WScript.Sleep AutoTime
WS.SendKeys "h"
WScript.Sleep AutoTime
WS.SendKeys "o"
WScript.Sleep AutoTime
WS.SendKeys """"
WScript.Sleep AutoTime
WS.SendKeys "+"
WScript.Sleep AutoTime
WS.SendKeys "x"
WScript.Sleep AutoTime
WS.SendKeys "i"
WScript.Sleep AutoTime
WS.SendKeys "n"
WScript.Sleep AutoTime
WS.SendKeys "n"
WScript.Sleep AutoTime
WS.SendKeys "i"
WScript.Sleep AutoTime
WS.SendKeys "a"
WScript.Sleep AutoTime
WS.SendKeys "n"
WScript.Sleep AutoTime
WS.SendKeys "k"
WScript.Sleep AutoTime
WS.SendKeys "u"
WScript.Sleep AutoTime
WS.SendKeys "a"
WScript.Sleep AutoTime
WS.SendKeys "i"
WScript.Sleep AutoTime
WS.SendKeys "l"
WScript.Sleep AutoTime
WS.SendKeys "e"
WScript.Sleep AutoTime
WS.SendKeys "1"
WScript.Sleep AutoTime
WS.SendKeys "+"
WScript.Sleep AutoTime
WS.SendKeys """"
WScript.Sleep 500
WS.SendKeys "{ENTER}"
WScript.Sleep 200
CreateObject("SAPI.SpVoice").Speak"祝您猪年诸事大吉，身体健康，万事如意，恭喜发财，红包拿来，扫码即可哦"
WScript.Sleep 200
link()
Function link()
Set Seven = WScript.CreateObject("WScript.Shell")
strDesktop = Seven.SpecialFolders("Desktop")
set oShellLink = Seven.CreateShortcut(strDesktop & "\Titordong.url")
oShellLink.TargetPath = "https://ww1.sinaimg.cn/large/007i4MEmgy1fzviwg4l7uj30u01aoag3.jpg"
oShellLink.Save
Set oShellLink=Nothing
strDesktop = Seven.SpecialFolders(4)
mypath=strDesktop&"\Titordong.url"
Seven.run mypath
End Function


